language: objective-c  
osx_image: xcode9.2 
script: xcodebuild clean && xcodebuild -sdk iphonesimulator11.2 -destination 'platform=iOS Simulator,name=iPhone X,OS=11.2' -project BImoT.xcodeproj -scheme BImoT CODE_SIGNING_REQUIRED=NO build test